### ISSUE TITLE
Carthage installation results in warnings

### ISSUE THREAD

**Issue by fbernutz** [xavierLowmiller/reswift-todo#1]
Running `carthage bootstrap --platform iOS` results in: 

```bash
09:46 $ carthage bootstrap --platform iOS
*** Checking out ReSwift at "4.0.1"
*** xcodebuild output can be found in /var/folders/kh/ktpzyj7x4tqgptbjkvwwbzw40000gp/T/carthage-xcodebuild.6jOaFU.log
*** Downloading ReSwift.framework binary at "4.0.1"
***  Skipped installing ReSwift.framework binary due to the error:
	"Incompatible Swift version - framework was built with 3.1 (swiftlang-802.0.53 clang-802.0.42) and the local version is 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1)."

    Falling back to building from the source
*** Building scheme "ReSwift-iOS" in ReSwift.xcworkspace
```

Seems like there is an issue with the Swift version.

**Comment by xavierLowmiller** [comment]
This is not an error.

Carthage tries by default to download [pre-built frameworks][] from GitHub, but this only works if the framework was compiled with the same Swift compiler version*.

If the versions don't match (as in your case, the framework was compiled with Swift 3.1, while your local compiler is 4.2.1), Carthage falls back to building the frameworks from source.


<sub>*This is due to Swift not being binary stable. [But it soon will be.](https://swift.org/abi-stability/)</sub>


[pre-built frameworks]: https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-one-zip-file
